<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/base.css">
    <title><?= $title ?></title>
    <script type="importmap">
        {
            "imports": {
                "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/+esm",
                "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.esm.min.js"
            }
        }
    </script>
    <script type="module" src="/assets/main.js" defer></script>
</head>

<body data-bs-theme="light">
    <nav class="navbar navbar-expand-lg bg-body-secondary">
        <div class="container-fluid">
            <span class="navbar-brand"><?= $title ?></span>
            <button id="theme" class="btn">
                <i class="bi bi-moon-fill"></i>
            </button>
        </div>
    </nav>
    <main class="container">
        <section id="uploader" class="text-center mt-5 border border-2 rounded p-5" role="button">
            <i class="bi bi-cloud-upload"></i>
            <p class="lead">Select or Drag</p>
            <small class="text-body-tertiary">
                Allowed Extension(s)&colon;
                <span class="font-monospace">.ttf</span>
            </small>
        </section>
        <section id="file">
            <input type="file" class="d-none" accept=".ttf">
            <p class="m-0 text-center text-danger d-none"></p>
        </section>
        <section id="fonts" class="my-5">
            <h3>All Fonts</h3>
            <p class="text-body-secondary">Browse all the available fonts to build your font group</p>
            <span class="text-info">Nothing Here!</span>
            <table class="table table-hover d-none">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Preview</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    <!-- <tr class="align-middle" role="button">
                        <th scope="row"></th>
                        <td></td>
                        <td>
                            <button class="btn" title="Delete">
                                <i class="bi bi-trash text-danger"></i>
                            </button>
                        </td>
                    </tr> -->
                </tbody>
            </table>
        </section>
        <section id="groups" class="my-5">
            <h3>All Font Groups</h3>
            <p class="text-body-secondary">List of all the available font groups</p>
            <span class="text-info">Nothing Here!</span>
            <table class="table table-hover d-none">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Fonts</th>
                        <th scope="col">Count</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    <!-- <tr class="align-middle" role="button">
                        <th scope="row"></th>
                        <td></td>
                        <td></td>
                        <td>
                            <button class="btn" title="Edit">
                                <i class="bi bi-pen text-info"></i>
                            </button>
                            <button class="btn" title="Delete">
                                <i class="bi bi-trash text-danger"></i>
                            </button>
                        </td>
                    </tr> -->
                </tbody>
            </table>
        </section>
        <section id="creation" class="my-5 d-none">
            <h3>Create Font Group</h3>
            <p class="text-body-secondary">Create a group with multiple fonts</p>
            <form>
                <input type="text" class="form-control" name="name" placeholder="Group Name" required>
                <article class="my-3">
                    <!-- <div class="row m-0 p-2 gap-2 align-items-center border rounded">
                        <div class="col p-0">
                            <select class="form-select" name="fonts[]" required>
                                <option selected>&dash;&dash; Select A Font &dash;&dash;</option>
                            </select>
                        </div>
                        <div class="col-auto p-0">
                            <button type="button" class="btn-close" disabled></button>
                        </div>
                    </div> -->
                </article>
                <aside class="d-flex align-items-center justify-content-between">
                    <button type="button" class="btn btn-outline-primary">Add Row</button>
                    <p class="m-0 text-danger d-none"></p>
                    <button type="submit" class="btn btn-primary" disabled>Create Group</button>
                </aside>
            </form>
        </section>
    </main>
</body>

</html>